const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require("fs");
const path = require("path");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function translateText(text, targetLang) {
  const model = genAI.getGenerativeModel({ model: "gemini-pro" });
  
  const prompt = `Olet ammattimainen kääntäjä. Käännä tämä Markdown-tiedosto kielelle ${targetLang}. 
    SÄILYTÄ kaikki Frontmatter-tiedot (--- välissä olevat tiedot) ja Markdown-syntaksi. 
    
    LISÄÄ tiedoston loppuun seuraava osio täsmälleen näin:
    
    ---
    ### 🛡️ Quality Assurance & Approvals
    *This content was translated from Finnish to ${targetLang} and generated by AI v.1.*
    - [ ] 🛠️ **Developer:** (Verified technical logic)
    - [ ] 📋 **Foreman:** (Approved for site use)
    - [ ] 🛡️ **Insurance:** (Risk assessment validated)
    - [ ] 👷 **Worker:** (Instructions understood)

    Teksti: ${text}`;
  
  const result = await model.generateContent(prompt);
  return result.response.text();
}

async function processFile(relativeFsPath) {
  console.log(`--- Ksitellään: ${relativeFsPath} ---`);
  
  // Puhdistetaan polku (poistetaan mahdolliset ./ alusta)
  const cleanRelativePath = relativeFsPath.replace(/^\.\//, '');
  const fullPath = path.resolve(process.cwd(), cleanRelativePath);
  
  if (!fs.existsSync(fullPath)) {
    console.error(`❌ Tiedostoa ei löydy: ${fullPath}`);
    return;
  }

  const content = fs.readFileSync(fullPath, "utf-8");

  // LOOPIN ESTO
  if (content.includes("generated by AI v.1")) {
    console.log(`⏭️ Hypätään yli: ${cleanRelativePath} (Jo käännetty)`);
    return;
  }

  const targetLangs = [
    { code: 'en', name: 'English' },
    { code: 'uk', name: 'Ukrainian' }
  ];

  for (const lang of targetLangs) {
    try {
      console.log(`🌍 Käännetään (${lang.name})...`);
      const translation = await translateText(content, lang.name);

      const fileName = path.basename(cleanRelativePath);
      // Lasketaan alikansio (esim. docs/tyomaa/ohje.md -> tyomaa)
      const subDir = path.dirname(cleanRelativePath).replace(/^docs\/?/, '');
      
      const targetDir = path.resolve(
        process.cwd(), 
        'i18n', lang.code, 'docusaurus-plugin-content-docs', 'current', subDir
      );

      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      const finalPath = path.join(targetDir, fileName);
      fs.writeFileSync(finalPath, translation);
      console.log(`✅ Tallennettu: ${finalPath}`);
    } catch (err) {
      console.error(`❌ Virhe (${lang.name}):`, err.message);
    }
  }
}

async function run() {
  const files = process.argv.slice(2);
  if (files.length === 0) {
    console.log("Ei muuttuneita tiedostoja.");
    return;
  }
  for (const file of files) {
    if (file.endsWith('.md') || file.endsWith('.mdx')) {
      await processFile(file);
    }
  }
}

run().catch(console.error);