const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require("fs");
const path = require("path");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function translateText(text, targetLang) {
  // 1. Käytetään MALLIA gemini-1.5-flash (tämä on varma valinta)
  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
  
  const prompt = `Olet ammattimainen kääntäjä. Käännä tämä Markdown-tiedosto kielelle ${targetLang}. 
                  SÄILYTÄ kaikki Frontmatter-tiedot (--- välissä olevat tiedot) ja Markdown-syntaksi. 
                  Teksti: ${text}`;
  
  try {
    // 2. Tehdään kutsu
    const result = await model.generateContent(prompt);
    // 3. Odotetaan vastausta (tämä on kriittinen muutos)
    const response = await result.response;
    const translatedText = response.text();
    
    return translatedText;
  } catch (err) {
    console.error(`Virhe Gemini-kutsussa: ${err.message}`);
    throw err;
  }
}

async function processFile(relativeFsPath) {
  console.log(`--- Ksitellään: ${relativeFsPath} ---`);
  
  // Puhdistetaan polku (poistetaan mahdolliset ./ alusta)
  const cleanRelativePath = relativeFsPath.replace(/^\.\//, '');
  const fullPath = path.resolve(process.cwd(), cleanRelativePath);
  
  if (!fs.existsSync(fullPath)) {
    console.error(`❌ Tiedostoa ei löydy: ${fullPath}`);
    return;
  }

  const content = fs.readFileSync(fullPath, "utf-8");

  // LOOPIN ESTO
  if (content.includes("generated by AI v.1")) {
    console.log(`⏭️ Hypätään yli: ${cleanRelativePath} (Jo käännetty)`);
    return;
  }

  const targetLangs = [
    { code: 'en', name: 'English' },
    { code: 'uk', name: 'Ukrainian' }
  ];

  for (const lang of targetLangs) {
    try {
      console.log(`🌍 Käännetään (${lang.name})...`);
      const translation = await translateText(content, lang.name);

      const fileName = path.basename(cleanRelativePath);
      // Lasketaan alikansio (esim. docs/tyomaa/ohje.md -> tyomaa)
      const subDir = path.dirname(cleanRelativePath).replace(/^docs\/?/, '');
      
      const targetDir = path.resolve(
        process.cwd(), 
        'i18n', lang.code, 'docusaurus-plugin-content-docs', 'current', subDir
      );

      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      const finalPath = path.join(targetDir, fileName);
      fs.writeFileSync(finalPath, translation);
      console.log(`✅ Tallennettu: ${finalPath}`);
    } catch (err) {
      console.error(`❌ Virhe (${lang.name}):`, err.message);
    }
  }
}

async function run() {
  const files = process.argv.slice(2);
  if (files.length === 0) {
    console.log("Ei muuttuneita tiedostoja.");
    return;
  }
  for (const file of files) {
    if (file.endsWith('.md') || file.endsWith('.mdx')) {
      await processFile(file);
    }
  }
}

run().catch(console.error);